import Head from "next/head";
import TodoDetail from "../../../src/components/units/detail/TodoDetail.container";
import Header from "../../../src/components/units/header/Header.container";

import { useRouter } from "next/router";

export default function DetailPage() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Codeit To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link
          href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css"
          rel="stylesheet"
        />
      </Head>

      <Header />
      <TodoDetail />
    </>
  );
}
