import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";
import Header from "../src/components/units/header/Header.container";
import TodoList from "../src/components/units/list/TodoList.container";
import AddTodo from "../src/components/units/add/AddTodo.container";
import { useEffect, useState } from "react";
import { Ilist } from "../src/commons/types/types";
import axios from "axios";
import { BASE_URL } from "../src/commons/api/api";

export default function Home() {
  const router = useRouter();
  const [totalLists, setTotalLists] = useState<Ilist[]>([]);
  // const [addTodo, setAddTodo] = useState("");
  // const router = useRouter();

  useEffect(() => {
    axios.get(BASE_URL).then((res) => {
      setTotalLists(res.data);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Codeit To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/todo-list-assignment/favicon.png" />
        <link
          href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <AddTodo totalLists={totalLists} />
      <TodoList />
    </>
  );
}
